---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Ge build
          command: |
            echo "Hello World!"
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Gradle build
          command: |
            echo "Hello World!"

          
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build_workflow:
    jobs:
    - build