--- 

version: 2
jobs:
  pr_check:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:4.8.2-jessie
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: mongo:3.4.4-jessie
    steps:
      - checkout
      - run:
          name: see check
          command: echo "Hello World"

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
